# Generated by Django 5.1.8 on 2025-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='inventario.categoriaproducto'),
        ),
    ]
